package io.github.matheuscarv69.exception;

public class ChamadoNaoEncontradoException extends RuntimeException {

    public ChamadoNaoEncontradoException() {
        super("Chamado n√£o encontrado.");
    }

}
